import { IMAGES } from "./Constants";

export const formatDate = (isoString) => {
  const date = new Date(isoString);
  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const year = date.getFullYear();
  return `${day}/${month}/${year}`;
};

export const stocklabel = (stock) => {
  if (stock === 0) {
    return "out of Stock ";
  } else if (stock < 10) {
    return "Limited Stock";
  } else {
    return "In Stock";
  }
};

export const landingHeroSlides = [
  {
    image: IMAGES.heroBackground1,
    title: "Premium Electronics",
    subtitle: "Discover the latest tech innovations",
    description: "Up to 50% off on premium headphones, smartwatches, and more",
    buttonText: "Shop Electronics",
  },
  {
    image: IMAGES.heroBackground2,
    title: "Fashion Forward",
    subtitle: "Style meets comfort",
    description: "Nammy in des ner clot ng and accessories",
    buttonText: "Explore Fashion",
  },

  {
    image: IMAGES.heroBackground3,
    title: "Home & Garden",
    subtitle: "Tansform your space",
    description: "Beautiful furniture and decor for every home",
    buttonText: "Shop Home",
  },
];

export const landingCategory = [
  {
    image: IMAGES.Category1,
    title: "Electronics",
    buttonClick: "Shop Electronics",
  },
  {
    image: IMAGES.heroBackground2,
    title: "Fashion",
    buttonClick: "Shop Fashion",
  },
  {
    image: IMAGES.heroBackground3,
    title: "Home & Garden",
    buttonClick: "Shop Home",
  },
  {
    image: IMAGES.Category4,
    title: "Sports",
    buttonClick: "Shop Sports",
  },
  {
    image: IMAGES.Category5,
    title: "Books",
    buttonClick: "Shop Books",
  },
  {
    image: IMAGES.Category6,
    title: "Beauty",
    buttonClick: "Shop Beauty",
  },
  {
    image: IMAGES.Category7,
    title: "Automotive",
    buttonClick: "Shop Automotive",
  },
  {
    image: IMAGES.Category8,
    title: "Kids & Baby",
    buttonClick: "Shop Kids",
  },
];

export const landingServices = [
  {
    icon: "Truck",
    title: "Free Shipping",
    subtitle: "Free shipping on orders over $50 worldwide",
  },
  {
    icon: "Shield",
    title: "Secure Payment",
    subtitle: "100% secure payment with SSL encryption",
  },
  {
    icon: "Headphones",
    title: "24/7 Support",
    subtitle: " Dedicated customer support available anytime",
  },
  {
    icon: "CreditCard",
    title: "Easy Returns",
    subtitle: "30-day return policy for your peace of mind",
  },
];

export const dummyProducts = [
  {
    _id: 1,
    name: "Men's Classic Cotton T-Shirt",
    category: "Mens",
    price: 19.99,
    rating: 4.5,
    stock: 120,
    description:
      "Soft and breathable cotton t-shirt perfect for everyday wear.",
    image: "/images/mens_tshirt.jpg",
  },
  {
    _id: 2,
    name: "Women's Summer Floral Dress",
    category: "Womens",
    price: 34.99,
    rating: 4.7,
    stock: 80,
    description: "Lightweight floral dress ideal for warm weather.",
    image: "/images/womens_dress.jpg",
  },
  {
    _id: 3,
    name: "Wireless Bluetooth Earbuds",
    category: "Electronics",
    price: 59.99,
    rating: 4.6,
    stock: 200,
    description: "Noise-cancelling wireless earbuds with long battery life.",
    image: "/images/earbuds.jpg",
  },
  {
    _id: 4,
    name: "4K Ultra HD Smart TV 55-inch",
    category: "Electronics",
    price: 499.99,
    rating: 4.8,
    stock: 35,
    description: "Stunning 4K display with built-in streaming apps.",
    image: "/images/smart_tv.jpg",
  },
  {
    _id: 5,
    name: "Adjustable Dumbbell Set (20kg)",
    category: "Sports",
    price: 89.99,
    rating: 4.4,
    stock: 60,
    description: "Compact dumbbell set with adjustable weights.",
    image: "/images/dumbbells.jpg",
  },
  {
    _id: 6,
    name: "Yoga Mat with Carrying Strap",
    category: "Sports",
    price: 25.99,
    rating: 4.5,
    stock: 100,
    description: "Non-slip yoga mat for home and gym workouts.",
    image: "/images/yoga_mat.jpg",
  },
  {
    _id: 7,
    name: "Modern LED Floor Lamp",
    category: "Home & Garden",
    price: 64.99,
    rating: 4.6,
    stock: 45,
    description: "Elegant LED lamp with adjustable brightness.",
    image: "/images/floor_lamp.jpg",
  },
  {
    _id: 8,
    name: "Bamboo Kitchen Utensil Set (6 pcs)",
    category: "Home & Garden",
    price: 22.99,
    rating: 4.3,
    stock: 150,
    description: "Eco-friendly bamboo utensils for cooking enthusiasts.",
    image: "/images/bamboo_utensils.jpg",
  },
  {
    _id: 9,
    name: "Men's Slim Fit Jeans",
    category: "Fashion",
    price: 49.99,
    rating: 4.5,
    stock: 90,
    description: "Durable and stylish denim jeans for everyday wear.",
    image: "/images/mens_jeans.jpg",
  },
  {
    _id: 10,
    name: "Women's Leather Handbag",
    category: "Fashion",
    price: 79.99,
    rating: 4.8,
    stock: 50,
    description: "Elegant and spacious leather handbag for any occasion.",
    image: "/images/leather_bag.jpg",
  },
  {
    _id: 11,
    name: "Hardcover Journal Notebook",
    category: "Books",
    price: 12.99,
    rating: 4.2,
    stock: 130,
    description: "A5 notebook with thick paper for journaling or notes.",
    image: "/images/journal.jpg",
  },
  {
    _id: 12,
    name: "Bestselling Thriller Novel",
    category: "Books",
    price: 16.99,
    rating: 4.7,
    stock: 75,
    description: "A gripping mystery novel with unexpected twists.",
    image: "/images/thriller_book.jpg",
  },
  {
    _id: 13,
    name: "Hydrating Face Serum",
    category: "Beauty",
    price: 24.99,
    rating: 4.6,
    stock: 110,
    description: "Vitamin C serum for glowing, hydrated skin.",
    image: "/images/face_serum.jpg",
  },
  {
    _id: 14,
    name: "Matte Lipstick Set (5 Colors)",
    category: "Beauty",
    price: 29.99,
    rating: 4.4,
    stock: 90,
    description: "Long-lasting lipstick set with rich, vibrant shades.",
    image: "/images/lipstick_set.jpg",
  },
  {
    _id: 15,
    name: "Car Vacuum Cleaner (Portable)",
    category: "Automotive",
    price: 39.99,
    rating: 4.5,
    stock: 70,
    description: "Handheld car vacuum for quick interior cleaning.",
    image: "/images/car_vacuum.jpg",
  },
  {
    _id: 16,
    name: "Dash Cam with Night Vision",
    category: "Automotive",
    price: 89.99,
    rating: 4.7,
    stock: 40,
    description: "Full HD dash cam for safe and reliable driving recording.",
    image: "/images/dash_cam.jpg",
  },
  {
    _id: 17,
    name: "Baby Swaddle Blanket Set",
    category: "Kids & Baby",
    price: 29.99,
    rating: 4.8,
    stock: 120,
    description: "Soft cotton swaddle blankets for newborn comfort.",
    image: "/images/swaddle_blanket.jpg",
  },
  {
    _id: 18,
    name: "Toddler Educational Toy Blocks",
    category: "Kids & Baby",
    price: 34.99,
    rating: 4.6,
    stock: 90,
    description: "Colorful building blocks for creative learning.",
    image: "/images/toy_blocks.jpg",
  },
  {
    _id: 19,
    name: "Wireless Gaming Mouse RGB",
    category: "Electronics",
    price: 44.99,
    rating: 4.5,
    stock: 85,
    description: "Ergonomic wireless gaming mouse with RGB lighting.",
    image: "/images/gaming_mouse.jpg",
  },
  {
    _id: 20,
    name: "Smart Fitness Tracker Watch",
    category: "Electronics",
    price: 69.99,
    rating: 4.6,
    stock: 100,
    description: "Track heart rate, steps, and sleep with Bluetooth sync.",
    image: "/images/fitness_tracker.jpg",
  },
  {
    _id: 21,
    name: "Men's Running Shoes",
    category: "Sports",
    price: 79.99,
    rating: 4.4,
    stock: 75,
    description: "Lightweight and breathable running shoes for men.",
    image: "/images/mens_running_shoes.jpg",
  },
  {
    _id: 22,
    name: "Women's Sports Bra",
    category: "Sports",
    price: 29.99,
    rating: 4.5,
    stock: 90,
    description: "Supportive and comfortable sports bra for workouts.",
    image: "/images/sports_bra.jpg",
  },
  {
    _id: 23,
    name: "Luxury Bed Sheet Set (Queen)",
    category: "Home & Garden",
    price: 59.99,
    rating: 4.8,
    stock: 60,
    description: "Soft and durable microfiber sheet set for ultimate comfort.",
    image: "/images/bed_sheet_set.jpg",
  },
  {
    _id: 24,
    name: "Succulent Plant Pack (5 pcs)",
    category: "Home & Garden",
    price: 24.99,
    rating: 4.7,
    stock: 80,
    description: "Low-maintenance succulents to brighten your home.",
    image: "/images/succulent_pack.jpg",
  },
  {
    _id: 25,
    name: "Unisex Denim Jacket",
    category: "Fashion",
    price: 69.99,
    rating: 4.5,
    stock: 65,
    description: "Classic denim jacket suitable for all seasons.",
    image: "/images/denim_jacket.jpg",
  },
  {
    _id: 26,
    name: "Cooking Recipe Book - Easy Meals",
    category: "Books",
    price: 18.99,
    rating: 4.6,
    stock: 90,
    description: "Quick and delicious recipes for everyday cooking.",
    image: "/images/recipe_book.jpg",
  },
  {
    _id: 27,
    name: "Luxury Perfume for Women (50ml)",
    category: "Beauty",
    price: 74.99,
    rating: 4.8,
    stock: 45,
    description: "Elegant fragrance with floral and woody notes.",
    image: "/images/perfume.jpg",
  },
  {
    _id: 28,
    name: "Kids Learning Tablet (Educational)",
    category: "Kids & Baby",
    price: 99.99,
    rating: 4.5,
    stock: 50,
    description: "Interactive tablet designed for children’s learning.",
    image: "/images/kids_tablet.jpg",
  },
  {
    _id: 29,
    name: "Car Phone Mount (Magnetic)",
    category: "Automotive",
    price: 19.99,
    rating: 4.4,
    stock: 130,
    description: "Secure magnetic phone holder for easy car access.",
    image: "/images/car_mount.jpg",
  },
  {
    _id: 30,
    name: "Electric Hair Trimmer Kit",
    category: "Beauty",
    price: 49.99,
    rating: 4.6,
    stock: 85,
    description: "Rechargeable grooming trimmer for men and women.",
    image: "/images/hair_trimmer.jpg",
  },
];